"""Acceptance tests for: Issue #918 — Coordinator blocked on READ of settings.local.json

Generated by acceptance-first pipeline mode.

Issue #918 reports that the hook write-protect logic appeared to fire on Read tool
calls targeting .claude/settings.local.json. Research confirmed the production code
is already correctly tool-name-gated at unified_pre_tool.py:4457 (Write/Edit gate)
and :4685 (Bash gate). The scope of this fix is to LOCK the correct behaviour in
place with a regression test class.

All criteria below are static file inspections (per STEP 6 placement classification
rule, those technically belong in tests/unit/, but we follow the existing
tests/genai/test_acceptance_*.py convention of marking acceptance criteria with
@pytest.mark.genai for traceability).
"""

import subprocess
from pathlib import Path

import pytest

from .conftest import PROJECT_ROOT

REGRESSION_TEST_FILE = (
    PROJECT_ROOT
    / "tests"
    / "unit"
    / "hooks"
    / "test_unified_pre_tool_false_positives.py"
)

UNIFIED_PRE_TOOL = (
    PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py"
)


@pytest.mark.genai
class TestAcceptanceIssue918:
    """Acceptance criteria from Issue #918."""

    def test_ac1_regression_class_exists(self):
        """AC1: New test class TestIssue918ReadToolNeverBlocksSettings exists."""
        content = REGRESSION_TEST_FILE.read_text()
        assert "class TestIssue918ReadToolNeverBlocksSettings" in content, (
            "Regression test class TestIssue918ReadToolNeverBlocksSettings must "
            f"exist in {REGRESSION_TEST_FILE.relative_to(PROJECT_ROOT)}"
        )

    def test_ac2_regression_class_docstring_cites_issue_and_lines(self):
        """AC2: Class docstring cites Issue #918 and gate line numbers 4457 and 4685."""
        content = REGRESSION_TEST_FILE.read_text()
        idx = content.find("class TestIssue918ReadToolNeverBlocksSettings")
        assert idx != -1, "Regression class must exist before docstring check"
        # Look at the next ~1500 chars for the class docstring
        window = content[idx : idx + 1500]
        assert "#918" in window or "Issue 918" in window, (
            "Class docstring must cite Issue #918"
        )
        assert "4457" in window, (
            "Class docstring must cite the Write/Edit gate line number 4457"
        )
        assert "4685" in window, (
            "Class docstring must cite the Bash gate line number 4685"
        )

    def test_ac3_regression_tests_pass(self):
        """AC3: All new regression tests PASS via pytest."""
        result = subprocess.run(
            [
                "pytest",
                str(REGRESSION_TEST_FILE),
                "-v",
                "--tb=short",
                "-k",
                "TestIssue918ReadToolNeverBlocksSettings",
            ],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            timeout=120,
        )
        assert result.returncode == 0, (
            f"Regression tests must pass. stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )

    def test_ac4_no_production_hook_modification(self):
        """AC4: unified_pre_tool.py is NOT modified by this change."""
        # Production hook source must be unchanged. We verify by checking that
        # the canonical gate lines are still at their expected line numbers and
        # contain the expected tool-name gate strings.
        lines = UNIFIED_PRE_TOOL.read_text().splitlines()
        # Line numbers are 1-indexed; the gates are at 4457 and 4685.
        # We allow a small drift window (+/- 5 lines) for trivial whitespace
        # changes from other unrelated edits.
        gate_write_edit_found = False
        gate_bash_found = False
        for i in range(max(0, 4457 - 6), min(len(lines), 4457 + 6)):
            if 'tool_name in ("Write", "Edit")' in lines[i]:
                gate_write_edit_found = True
                break
        for i in range(max(0, 4685 - 6), min(len(lines), 4685 + 6)):
            if 'tool_name == "Bash"' in lines[i]:
                gate_bash_found = True
                break
        assert gate_write_edit_found, (
            "Write/Edit tool-name gate must still exist near line 4457 in "
            "unified_pre_tool.py — Issue #918 scope forbids modifying this file"
        )
        assert gate_bash_found, (
            "Bash tool-name gate must still exist near line 4685 in "
            "unified_pre_tool.py — Issue #918 scope forbids modifying this file"
        )
