"""Acceptance tests for: Runtime observability fix + continuous improvement loop.

Generated by acceptance-first pipeline mode.
Validates that Agent/Skill tool calls are properly captured in activity logs
and that the continuous improvement analyst can detect pipeline bypasses.

Related issues: #380 (subagent_type lost), #408 (pipeline bypass), #411 (naming collisions)
"""

import re

import pytest

from .conftest import PROJECT_ROOT

pytestmark = [pytest.mark.genai]

PLUGIN_ROOT = PROJECT_ROOT / "plugins" / "autonomous-dev"
LOGGER_PATH = PLUGIN_ROOT / "hooks" / "session_activity_logger.py"
VALIDATOR_PATH = PLUGIN_ROOT / "lib" / "pipeline_intent_validator.py"
ANALYST_PATH = PLUGIN_ROOT / "agents" / "continuous-improvement-analyst.md"
PRE_TOOL_PATH = PLUGIN_ROOT / "hooks" / "unified_pre_tool.py"


class TestAgentToolObservability:
    """Agent tool calls must capture subagent_type, not just key names."""

    def test_logger_handles_agent_tool_name(self, genai):
        """The _summarize_input function must handle 'Agent' tool (not just 'Task')."""
        source = LOGGER_PATH.read_text()

        # Deterministic: "Agent" must appear in _summarize_input tool name checks
        match = re.search(
            r"(def _summarize_input\(.*?\n(?:(?!^def ).*\n)*)", source, re.MULTILINE
        )
        assert match, "_summarize_input function not found"
        summarize_fn = match.group(1)

        assert '"Agent"' in summarize_fn, (
            '_summarize_input does not handle "Agent" tool — '
            "subagent_type will not be captured (issue #380)"
        )

        # GenAI: verify the Agent handler captures the same fields as Task
        result = genai.judge(
            question="Does the _summarize_input function handle 'Agent' tool calls with the same detail as 'Task' tool calls?",
            context=summarize_fn,
            criteria=(
                "Both 'Agent' and 'Task' tool names should capture: subagent_type, "
                "description, pipeline_action='agent_invocation', and prompt_word_count. "
                "Score 8+ if both are handled identically."
            ),
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_logger_handles_skill_tool(self, genai):
        """The _summarize_input function must handle 'Skill' tool invocations."""
        source = LOGGER_PATH.read_text()

        match = re.search(
            r"(def _summarize_input\(.*?\n(?:(?!^def ).*\n)*)", source, re.MULTILINE
        )
        assert match, "_summarize_input function not found"
        summarize_fn = match.group(1)

        assert '"Skill"' in summarize_fn, (
            '_summarize_input does not handle "Skill" tool — '
            "skill invocations will not be tracked"
        )

    def test_result_word_count_covers_agent_tool(self, genai):
        """_add_result_word_count must fire for 'Agent' tool, not just 'Task'."""
        source = LOGGER_PATH.read_text()

        match = re.search(
            r"(def _add_result_word_count\(.*?\n(?:(?!^def ).*\n)*)",
            source,
            re.MULTILINE,
        )
        assert match, "_add_result_word_count function not found"
        word_count_fn = match.group(1)

        assert '"Agent"' in word_count_fn, (
            '_add_result_word_count does not handle "Agent" tool — '
            "context dropping detection will be blind"
        )


class TestPipelineIntentValidatorObservability:
    """Pipeline intent validator must parse both 'Task' and 'Agent' tool names."""

    def test_validator_accepts_agent_tool_name(self, genai):
        """parse_session_logs must filter on both 'Task' and 'Agent' tool names."""
        source = VALIDATOR_PATH.read_text()

        # Deterministic: "Agent" must appear in tool name filtering
        assert '"Agent"' in source, (
            'pipeline_intent_validator does not handle "Agent" tool name — '
            "all pipeline events will be missed"
        )

        # GenAI: verify all filtering locations handle both names
        result = genai.judge(
            question="Does the pipeline intent validator handle both 'Task' and 'Agent' tool names in ALL filtering locations?",
            context=source,
            criteria=(
                "Every location that filters on tool name (parse_session_logs, "
                "validate_step_ordering, detect_context_dropping, detect_parallelization_violations) "
                "must accept both 'Task' and 'Agent'. A constant like AGENT_TOOL_NAMES is ideal. "
                "Score 8+ if all locations are covered."
            ),
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]


class TestPreToolUseLogging:
    """PreToolUse decision logs must include agent identity for Agent/Skill tools."""

    def test_pretool_logs_agent_identity(self, genai):
        """_log_pretool_activity must capture subagent_type for Agent tool calls."""
        source = PRE_TOOL_PATH.read_text()

        # Extract the _log_pretool_activity function
        match = re.search(
            r"(def _log_pretool_activity\(.*?\n(?:(?!^def ).*\n)*)",
            source,
            re.MULTILINE,
        )
        assert match, "_log_pretool_activity function not found"
        log_fn = match.group(1)

        assert '"Agent"' in log_fn, (
            '_log_pretool_activity does not handle "Agent" tool — '
            "PreToolUse logs will not include agent identity"
        )


class TestContinuousImprovementLoop:
    """The CI analyst must detect pipeline bypasses using the now-captured data."""

    def test_analyst_references_both_tool_names(self, genai):
        """Analyst documentation must reference both 'Task' and 'Agent' tool names."""
        analyst = ANALYST_PATH.read_text()

        # Must mention Agent tool name for accurate log parsing guidance
        has_agent_ref = '"Agent"' in analyst or "'Agent'" in analyst or "Agent" in analyst
        assert has_agent_ref, (
            "Analyst does not reference 'Agent' tool name — "
            "will look for wrong tool name in logs"
        )

    def test_analyst_can_detect_pipeline_bypass_with_new_data(self, genai):
        """With subagent_type captured, analyst should detect when pipeline agents are missing."""
        analyst = ANALYST_PATH.read_text()
        validator = VALIDATOR_PATH.read_text()

        result = genai.judge(
            question="Can the continuous improvement system detect when /implement pipeline agents are skipped or invoked out of order?",
            context=f"--- Analyst Agent ---\n{analyst[:3000]}\n\n--- Pipeline Validator ---\n{validator[:3000]}",
            criteria=(
                "The system should detect: (1) missing pipeline agents (e.g., implementer invoked "
                "without researcher), (2) out-of-order invocation (implementer before planner), "
                "(3) direct agent invocation outside pipeline context. "
                "Score 8+ if all three are detectable."
            ),
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_backward_compatibility_with_task_tool_name(self, genai):
        """Old logs with 'Task' tool name must still be parseable."""
        validator = VALIDATOR_PATH.read_text()

        # Deterministic: "Task" must still appear in filtering
        assert '"Task"' in validator, (
            'pipeline_intent_validator dropped "Task" tool name — '
            "old logs will not be parseable"
        )
