"""Acceptance tests for: Issue #410 - batch worktree cleanup CWD protection

Generated by acceptance-first pipeline mode.
Validates that worktree cleanup properly handles CWD being inside the worktree.
"""

import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent


@pytest.mark.genai
class TestAcceptanceWorktreeCwdFix:
    """Acceptance criteria from issue #410."""

    def test_implement_batch_instructs_cd_before_cleanup(self, genai):
        """STEP B4 must instruct coordinator to cd to main repo before deleting worktree."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement-batch.md").read_text()
        result = genai.judge(
            question="Does STEP B4 explicitly instruct the coordinator to change directory (cd) to the main repository BEFORE deleting/removing the worktree directory?",
            context=context,
            criteria="STEP B4 must contain an explicit 'cd' command to the main/parent repo BEFORE any rm -rf or worktree removal command. The cd and rm must be in the same bash block or the cd must precede the rm.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_implement_batch_forbids_cwd_deletion(self, genai):
        """STEP B4 must have a FORBIDDEN rule about deleting worktree while CWD is inside it."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/commands/implement-batch.md").read_text()
        result = genai.judge(
            question="Does STEP B4 contain a FORBIDDEN rule that explicitly prohibits deleting a worktree directory while the shell CWD is inside it?",
            context=context,
            criteria="There must be a FORBIDDEN item (using the word FORBIDDEN or equivalent enforcement language) that warns against deleting the worktree while CWD is inside it, referencing Issue #410.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_cleanup_worktree_has_cwd_protection(self, genai):
        """cleanup_worktree() in batch_git_finalize.py must check and handle CWD inside worktree."""
        context = (PROJECT_ROOT / "plugins/autonomous-dev/lib/batch_git_finalize.py").read_text()
        result = genai.judge(
            question="Does the cleanup_worktree() function check if the current working directory is inside the worktree and change to a safe directory before deleting?",
            context=context,
            criteria="The function must: (1) check if Path.cwd() is inside the worktree_path, (2) if so, os.chdir() to the main repo before deletion, (3) return information about the safe CWD so callers know where they are.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]

    def test_post_cleanup_shell_commands_work(self, genai):
        """Unit tests must verify that shell commands work after worktree cleanup from inside."""
        context = (PROJECT_ROOT / "tests/unit/lib/test_batch_git_finalize.py").read_text()
        result = genai.judge(
            question="Do the tests verify that after cleanup_worktree() is called while CWD is inside the worktree, the CWD is moved to a valid directory and subsequent operations work?",
            context=context,
            criteria="There must be a test that: (1) sets CWD inside the worktree, (2) calls cleanup_worktree(), (3) verifies CWD is now outside the deleted worktree in a valid directory.",
            category="architecture",
        )
        assert result["band"] != "hard_fail", result["reasoning"]
