#!/usr/bin/env bash
# Backfill: file GitHub issues for the 2 real Low-severity security advisories
# deferred from #1175 (STEP 4.8 plan freshness re-verification).
#
# These were caught by the security-auditor on #1175 but never filed as
# tracking issues because the coordinator did not yet enforce ADVISORY-FINDINGS
# parsing (the gap closed by #1180). This script files them retroactively.
#
# Usage:
#   bash scripts/backfill_1175_security_advisories.sh
#
# Idempotency: dedup queries each title before filing. Safe to re-run.

set -euo pipefail

# Verify gh CLI is available and authenticated.
if ! command -v gh >/dev/null 2>&1; then
  echo "[ERROR] gh CLI not found on PATH. Install: https://cli.github.com/" >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "[ERROR] gh CLI is not authenticated. Run: gh auth login" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Finding 1: Path-traversal in verify_paths_exist()
# ---------------------------------------------------------------------------
TITLE_1="[Security advisory] Path-traversal risk in verify_paths_exist (plan_freshness.py:54-74)"
BODY_1=$(cat <<'EOF'
**Source**: Security-auditor finding on Issue #1175 (STEP 4.8 plan freshness re-verification), retroactively filed via `scripts/backfill_1175_security_advisories.sh` after #1180 closed the ADVISORY-FINDINGS tracking gap.

**Severity**: Low

**Location**: `plugins/autonomous-dev/lib/plan_freshness.py:54-74` — function `verify_paths_exist()`

**Finding**: The `verify_paths_exist()` function resolves user-supplied path strings (extracted from plan markdown via the `_FILE_PATH_REGEX`) under `repo_root` without normalizing or canonicalizing them. A plan containing path strings like `../../etc/passwd` or `subdir/../../../sensitive.py` would be checked as `repo_root / "../../etc/passwd"`, potentially escaping the repo root.

**Attack vector**: Low severity because (a) the function only checks `.exists()` — it does not read file content or expose results to an attacker, and (b) the input source is the plan markdown, which is generated by a trusted planner agent. However, the lack of path canonicalization is a defense-in-depth gap.

**Recommendation**: Resolve and verify each candidate path stays within `repo_root` before the `.exists()` check:
```python
resolved = (repo_root / path_str).resolve()
if not str(resolved).startswith(str(repo_root.resolve())):
    # Treat as missing or raise; do not check .exists() on out-of-root paths.
    missing.append(path_str)
    continue
```

**Acceptance**: A regression test in `tests/unit/lib/` that asserts a plan containing `../` traversal sequences is rejected (treated as missing) rather than escaping the repo root.

Labels: `security`, `auto-improvement`
EOF
)

# ---------------------------------------------------------------------------
# Finding 2: ReDoS in _FILE_PATH_REGEX
# ---------------------------------------------------------------------------
TITLE_2="[Security advisory] ReDoS risk in _FILE_PATH_REGEX (plan_freshness.py:31)"
BODY_2=$(cat <<'EOF'
**Source**: Security-auditor finding on Issue #1175 (STEP 4.8 plan freshness re-verification), retroactively filed via `scripts/backfill_1175_security_advisories.sh` after #1180 closed the ADVISORY-FINDINGS tracking gap.

**Severity**: Low

**Location**: `plugins/autonomous-dev/lib/plan_freshness.py:31` — module-level constant `_FILE_PATH_REGEX`

**Finding**: The regex `[\w/.-]+\.(py|md|json|yaml|sh|ts|js)` uses an unbounded `[\w/.-]+` character class. While Python's `re` module does not have catastrophic backtracking in the classical sense (the pattern has no nested quantifiers), `finditer` over very large plan markdown blobs with adversarial input could exhibit superlinear scanning time. Low severity because (a) input is trusted (planner-generated), (b) Python's `re` is non-backtracking for this pattern shape, and (c) plan size is bounded by the planner's output budget.

**Attack vector**: Theoretical only — would require an attacker to control plan content AND produce a multi-megabyte plan with adversarial padding. Both pre-conditions are absent in the current pipeline.

**Recommendation**: Bound the path length explicitly. Either (a) cap the quantifier `[\w/.-]{1,512}\.(py|md|json|yaml|sh|ts|js)`, or (b) pre-truncate `plan_content` to a maximum size before regex scanning (e.g., 1 MiB). Option (a) is preferred because it preserves error visibility — overlong paths simply fail to match.

**Acceptance**: A regression test in `tests/unit/lib/` that confirms a plan containing a single 100 KB run of `[\w/.-]` characters completes regex extraction in <100 ms (or, with the cap, returns no false matches).

Labels: `security`, `auto-improvement`
EOF
)

# ---------------------------------------------------------------------------
# Dedup + file helper
# ---------------------------------------------------------------------------
file_if_new() {
  local title="$1"
  local body="$2"

  # Dedup: search for an open issue with the same title (security + auto-improvement labels).
  local existing
  existing=$(gh issue list --label security --label auto-improvement --state open --search "$title" --json title,number 2>/dev/null || echo "[]")

  if echo "$existing" | grep -q "$title" 2>/dev/null; then
    echo "[SKIP] Already filed: $title"
    return 0
  fi

  echo "[FILE] $title"
  gh issue create \
    --title "$title" \
    --body "$body" \
    --label security \
    --label auto-improvement
}

file_if_new "$TITLE_1" "$BODY_1"
file_if_new "$TITLE_2" "$BODY_2"

echo "[DONE] Backfill complete."
