#!/usr/bin/env python3
"""Measure IntentClassifier accuracy against the real corpus.

Runs the real IntentClassifier from lib/intent_classifier.py against each
entry in the corpus file, computes per-class precision/recall/F1, builds
a confusion matrix, and identifies the bottom-3 underperforming classes.

Optionally writes results to docs/intent_classifier_calibration.json and
splices a Markdown report into docs/INTENT-CLASSIFICATION.md (idempotent).

Usage:
    python scripts/measure_intent_classifier.py \\
        --corpus-path tests/fixtures/intent_classifier_real_corpus.json \\
        --baseline-output docs/intent_classifier_calibration.json \\
        --update-docs

GitHub Issue: #1043
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
_SCRIPT_DIR = Path(__file__).parent.resolve()
_PROJECT_ROOT = _SCRIPT_DIR.parent
_LIB_DIR = _PROJECT_ROOT / "plugins" / "autonomous-dev" / "lib"
_HOOKS_DIR = _PROJECT_ROOT / "plugins" / "autonomous-dev" / "hooks"

for _p in [str(_LIB_DIR), str(_HOOKS_DIR)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_DEFAULT_CORPUS = _PROJECT_ROOT / "tests" / "fixtures" / "intent_classifier_real_corpus.json"
_DEFAULT_BASELINE = _PROJECT_ROOT / "docs" / "intent_classifier_calibration.json"
_DEFAULT_DOCS_PATH = _PROJECT_ROOT / "docs" / "INTENT-CLASSIFICATION.md"

_MARKER_BEGIN = "<!-- BEGIN: M2 calibration metrics (auto-generated by scripts/measure_intent_classifier.py) -->"
_MARKER_END = "<!-- END: M2 calibration metrics -->"

NON_SWE_CLASSES = {
    "doc",
    "config",
    "typo",
    "status_query",
    "conversation",
    "exploration",
    "triage",
    "remote_ops",
    "scratch",
}

ALL_CLASSES = {
    "security_critical",
    "implement",
    "refactor",
    "test",
    "doc",
    "config",
    "typo",
    "status_query",
    "conversation",
    "exploration",
    "triage",
    "remote_ops",
    "scratch",
}


# ---------------------------------------------------------------------------
# Metric computation
# ---------------------------------------------------------------------------

def compute_metrics(
    predictions: List[str],
    ground_truth: List[str],
    classes: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Compute per-class precision, recall, F1, and macro F1.

    Args:
        predictions: Predicted intent class labels
        ground_truth: Ground truth intent class labels
        classes: Optional explicit class list (auto-detected if None)

    Returns:
        Dict with 'per_class' metrics, 'macro_f1', and 'confusion_matrix'
    """
    if classes is None:
        classes = sorted(set(ground_truth) | set(predictions))

    # Confusion matrix as nested dict: cm[true][pred] = count
    cm: Dict[str, Dict[str, int]] = {c: defaultdict(int) for c in classes}
    for gt, pred in zip(ground_truth, predictions):
        if gt in cm:
            cm[gt][pred] += 1
        else:
            # Unknown true class — add it
            cm[gt] = defaultdict(int)
            cm[gt][pred] += 1

    per_class: Dict[str, Dict[str, float]] = {}
    f1_values: List[float] = []

    for cls in classes:
        # True positives: predicted cls AND true is cls
        tp = cm.get(cls, {}).get(cls, 0)

        # False positives: predicted cls but true is NOT cls
        fp = sum(cm.get(other, {}).get(cls, 0) for other in classes if other != cls)

        # False negatives: true is cls but predicted something else
        fn = sum(cm.get(cls, {}).get(other, 0) for other in classes if other != cls)

        support = tp + fn
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1 = (
            2 * precision * recall / (precision + recall)
            if (precision + recall) > 0
            else 0.0
        )

        per_class[cls] = {
            "precision": round(precision, 4),
            "recall": round(recall, 4),
            "f1": round(f1, 4),
            "support": support,
        }
        if support > 0:
            f1_values.append(f1)

    macro_f1 = sum(f1_values) / len(f1_values) if f1_values else 0.0

    # Serialize confusion matrix (nested dicts → JSON-friendly)
    cm_serializable: Dict[str, Dict[str, int]] = {
        cls: dict(cm.get(cls, {})) for cls in classes
    }

    return {
        "per_class": per_class,
        "macro_f1": round(macro_f1, 4),
        "confusion_matrix": cm_serializable,
    }


def identify_bottom_n(
    per_class: Dict[str, Dict[str, float]],
    n: int = 3,
    exclude: Optional[set] = None,
) -> List[str]:
    """Identify the N worst-performing classes by F1 score.

    Excludes classes with zero support (can't meaningfully measure them).

    Args:
        per_class: Per-class metrics dict from compute_metrics
        n: Number of bottom performers to return
        exclude: Set of class names to exclude from ranking

    Returns:
        List of class names, worst first
    """
    if exclude is None:
        exclude = {"security_critical"}  # Never penalize security_critical in bottom-3

    ranked = [
        (cls, metrics["f1"])
        for cls, metrics in per_class.items()
        if cls not in exclude and metrics.get("support", 0) > 0
    ]
    ranked.sort(key=lambda x: x[1])
    return [cls for cls, _ in ranked[:n]]


# ---------------------------------------------------------------------------
# Classifier wrapper
# ---------------------------------------------------------------------------

def classify_with_real_classifier(prompt: str) -> str:
    """Classify a prompt using the real IntentClassifier.

    Falls back to 'ambiguous' if the classifier is unavailable.

    Args:
        prompt: User prompt to classify

    Returns:
        Intent class string
    """
    try:
        from intent_classifier import IntentClassifier  # type: ignore[import-not-found]
        classifier = IntentClassifier.from_config()
        result = classifier.classify(prompt)
        return result.intent.value if hasattr(result.intent, "value") else str(result.intent)
    except Exception as e:
        # Degrade gracefully if classifier unavailable
        return "ambiguous"


# ---------------------------------------------------------------------------
# Markdown report generation
# ---------------------------------------------------------------------------

def _build_markdown_report(
    per_class: Dict[str, Dict[str, float]],
    macro_f1: float,
    bottom_3: List[str],
    corpus_size: int,
    generated_at: str,
) -> str:
    """Build the Markdown calibration metrics section.

    Args:
        per_class: Per-class metrics
        macro_f1: Macro-averaged F1
        bottom_3: Bottom-3 underperforming classes
        corpus_size: Total corpus entries measured
        generated_at: ISO8601 timestamp

    Returns:
        Markdown string for the calibration section
    """
    lines = [
        _MARKER_BEGIN,
        "## Calibration Metrics (M2, Issue #1043)",
        "",
        f"_Generated at: {generated_at} | Corpus size: {corpus_size}_",
        "",
        f"**Macro F1: {macro_f1:.3f}**",
        "",
        "### Per-Class Metrics",
        "",
        "| Class | Precision | Recall | F1 | Support |",
        "|-------|-----------|--------|----|---------|",
    ]

    for cls in sorted(ALL_CLASSES):
        m = per_class.get(cls, {"precision": 0.0, "recall": 0.0, "f1": 0.0, "support": 0})
        lines.append(
            f"| `{cls}` | {m['precision']:.3f} | {m['recall']:.3f} | {m['f1']:.3f} | {m['support']} |"
        )

    lines += [
        "",
        "### Bottom-3 Underperformers",
        "",
        "These classes had the lowest F1 scores (excluding `security_critical`):",
        "",
    ]
    for i, cls in enumerate(bottom_3, 1):
        m = per_class.get(cls, {"f1": 0.0})
        lines.append(f"{i}. `{cls}` — F1: {m['f1']:.3f}")

    lines += [
        "",
        "**Future work**: Targeted augmentation of training fixtures for the bottom-3 classes "
        "is tracked as a follow-up to Issue #1043. This report MEASURES; the follow-up TUNES.",
        "",
        "### Methodology",
        "",
        "- Corpus: `tests/fixtures/intent_classifier_real_corpus.json`",
        "- Two-judge unanimous agreement (Anthropic + non-Anthropic via OpenRouter)",
        "  OR synthetic-fallback when API keys unavailable",
        "- Holdout entries excluded from accuracy gate but included in support counts",
        "- Regression policy: per-class F1 must not drop >0.05 from baseline; macro F1 must not drop >0.03",
        "",
        _MARKER_END,
    ]
    return "\n".join(lines)


def splice_docs(docs_path: Path, new_section: str) -> None:
    """Idempotently splice the calibration section into INTENT-CLASSIFICATION.md.

    Uses HTML comment markers. If the section already exists, it is replaced.
    If not, it is appended at the end.

    Args:
        docs_path: Path to INTENT-CLASSIFICATION.md
        new_section: Markdown content between the markers (inclusive)
    """
    if not docs_path.exists():
        docs_path.write_text(new_section + "\n")
        return

    content = docs_path.read_text()

    if _MARKER_BEGIN in content and _MARKER_END in content:
        # Replace existing section
        before = content[: content.index(_MARKER_BEGIN)]
        after = content[content.index(_MARKER_END) + len(_MARKER_END) :]
        new_content = before + new_section + after
    else:
        # Append at end
        new_content = content.rstrip() + "\n\n" + new_section + "\n"

    docs_path.write_text(new_content)


# ---------------------------------------------------------------------------
# Main measurement
# ---------------------------------------------------------------------------

def measure_corpus(
    corpus_path: Path,
    *,
    include_holdout: bool = False,
) -> Tuple[Dict[str, Any], List[str], List[str]]:
    """Load corpus and measure classifier performance.

    Args:
        corpus_path: Path to corpus JSON file
        include_holdout: If True, include holdout entries in measurement

    Returns:
        Tuple of (metrics_dict, ground_truth_list, prediction_list)
    """
    corpus = json.loads(corpus_path.read_text())
    entries = corpus.get("entries", [])

    if not include_holdout:
        entries = [e for e in entries if not e.get("holdout", False)]

    ground_truth: List[str] = []
    predictions: List[str] = []

    total = len(entries)
    print(f"INFO: Measuring {total} entries...", file=sys.stderr)

    for i, entry in enumerate(entries):
        if (i + 1) % 10 == 0:
            print(f"INFO: Progress: {i + 1}/{total}", file=sys.stderr)
        gt = entry.get("label", "")
        pred = classify_with_real_classifier(entry["prompt"])
        # Normalize 'ambiguous' to a consistent string
        if pred.lower() in {"ambiguous", "intclass.ambiguous"}:
            pred = "ambiguous"
        ground_truth.append(gt)
        predictions.append(pred)

    all_classes = sorted(ALL_CLASSES | {"ambiguous"})
    metrics = compute_metrics(predictions, ground_truth, classes=sorted(ALL_CLASSES))
    return metrics, ground_truth, predictions


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """CLI entry point for measurement."""
    parser = argparse.ArgumentParser(
        description="Measure IntentClassifier accuracy against corpus"
    )
    parser.add_argument(
        "--corpus-path",
        type=Path,
        default=_DEFAULT_CORPUS,
        help="Path to corpus JSON file",
    )
    parser.add_argument(
        "--baseline-output",
        type=Path,
        default=_DEFAULT_BASELINE,
        help="Output path for baseline JSON",
    )
    parser.add_argument(
        "--update-docs",
        action="store_true",
        help="Splice calibration metrics into docs/INTENT-CLASSIFICATION.md",
    )
    parser.add_argument(
        "--include-holdout",
        action="store_true",
        help="Include holdout entries in measurement",
    )
    args = parser.parse_args()

    if not args.corpus_path.exists():
        print(f"ERROR: Corpus file not found: {args.corpus_path}", file=sys.stderr)
        sys.exit(1)

    metrics, ground_truth, predictions = measure_corpus(
        args.corpus_path,
        include_holdout=args.include_holdout,
    )

    per_class = metrics["per_class"]
    macro_f1 = metrics["macro_f1"]

    bottom_3 = identify_bottom_n(per_class, n=3, exclude={"security_critical"})

    corpus = json.loads(args.corpus_path.read_text())
    corpus_size = len(corpus.get("entries", []))

    generated_at = datetime.now(timezone.utc).isoformat()

    baseline = {
        "_schema_version": 1,
        "generated_at": generated_at,
        "corpus_size": corpus_size,
        "per_class": per_class,
        "macro_f1": macro_f1,
        "confusion_matrix": metrics["confusion_matrix"],
        "bottom_3_underperformers": bottom_3,
    }

    # Print summary
    print("\n" + "=" * 60)
    print("INTENT CLASSIFIER CALIBRATION RESULTS")
    print("=" * 60)
    print(f"Corpus size: {corpus_size}")
    print(f"Macro F1: {macro_f1:.4f}")
    print()
    print(f"{'Class':<20} {'Precision':>10} {'Recall':>10} {'F1':>10} {'Support':>8}")
    print("-" * 62)
    for cls in sorted(ALL_CLASSES):
        m = per_class.get(cls, {"precision": 0.0, "recall": 0.0, "f1": 0.0, "support": 0})
        print(
            f"{cls:<20} {m['precision']:>10.3f} {m['recall']:>10.3f} "
            f"{m['f1']:>10.3f} {m['support']:>8}"
        )
    print()
    print(f"Bottom-3 underperformers (excl. security_critical): {bottom_3}")
    print("=" * 60)

    # Write baseline
    args.baseline_output.parent.mkdir(parents=True, exist_ok=True)
    args.baseline_output.write_text(json.dumps(baseline, indent=2))
    print(f"INFO: Baseline written to {args.baseline_output}", file=sys.stderr)

    # Update docs if requested
    if args.update_docs:
        markdown = _build_markdown_report(
            per_class, macro_f1, bottom_3, corpus_size, generated_at
        )
        splice_docs(_DEFAULT_DOCS_PATH, markdown)
        print(
            f"INFO: Calibration metrics spliced into {_DEFAULT_DOCS_PATH}",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
