#!/usr/bin/env python3
"""Measure IntentClassifier accuracy against the real corpus.

Runs the real IntentClassifier from lib/intent_classifier.py against each
entry in the corpus file, computes per-class precision/recall/F1, builds
a confusion matrix, and identifies the bottom-3 underperforming classes.

Optionally writes results to docs/intent_classifier_calibration.json and
splices a Markdown report into docs/INTENT-CLASSIFICATION.md (idempotent).

Usage:
    python scripts/measure_intent_classifier.py \\
        --corpus-path tests/fixtures/intent_classifier_real_corpus.json \\
        --baseline-output docs/intent_classifier_calibration.json \\
        --update-docs

GitHub Issue: #1043
"""

from __future__ import annotations

import argparse
import json
import math
import os
import re
import sqlite3
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
_SCRIPT_DIR = Path(__file__).parent.resolve()
_PROJECT_ROOT = _SCRIPT_DIR.parent
_LIB_DIR = _PROJECT_ROOT / "plugins" / "autonomous-dev" / "lib"
_HOOKS_DIR = _PROJECT_ROOT / "plugins" / "autonomous-dev" / "hooks"

for _p in [str(_LIB_DIR), str(_HOOKS_DIR)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

# Required for _read_jsonl_safely import from hook_block_summary
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_DEFAULT_CORPUS = _PROJECT_ROOT / "tests" / "fixtures" / "intent_classifier_real_corpus.json"
_DEFAULT_BASELINE = _PROJECT_ROOT / "docs" / "intent_classifier_calibration.json"
_DEFAULT_DOCS_PATH = _PROJECT_ROOT / "docs" / "INTENT-CLASSIFICATION.md"

_MARKER_BEGIN = "<!-- BEGIN: M2 calibration metrics (auto-generated by scripts/measure_intent_classifier.py) -->"
_MARKER_END = "<!-- END: M2 calibration metrics -->"

# ---------------------------------------------------------------------------
# Telemetry validation constants (Issue #1077, Phase B)
# ---------------------------------------------------------------------------

_DEFAULT_TELEMETRY_LOG = _PROJECT_ROOT / ".claude" / "logs" / "hook-blocks.jsonl"
_DEFAULT_SESSIONS_DB = Path.home() / ".claude" / "archive" / "sessions.db"
_DEFAULT_TELEMETRY_OUTPUT = (
    _PROJECT_ROOT / "docs" / "intent_classifier_telemetry_validation.json"
)
_SYNTHETIC_SESSION_PREFIX = "phase-e-test-"
_INSUFFICIENT_SAMPLE_THRESHOLD = 50
_AGGREGATE_TOOL_THRESHOLD = 8
_AGGREGATE_BYTES_THRESHOLD = 4096
_TELEMETRY_SCHEMA_VERSION = 1

_IMPLEMENT_REGEX_PATTERNS = (
    re.compile(r"^\s*/implement\b", re.IGNORECASE),
    re.compile(r"^\s*/refactor\b", re.IGNORECASE),
    re.compile(r"^\s*/fix\b", re.IGNORECASE),
)

_MODE_SKIP_REASON_RE = re.compile(r"^mode_skip:([a-z_]+)$")

NON_SWE_CLASSES = {
    "doc",
    "config",
    "typo",
    "status_query",
    "conversation",
    "exploration",
    "triage",
    "remote_ops",
    "scratch",
}

ALL_CLASSES = {
    "security_critical",
    "implement",
    "refactor",
    "test",
    "doc",
    "config",
    "typo",
    "status_query",
    "conversation",
    "exploration",
    "triage",
    "remote_ops",
    "scratch",
}


# ---------------------------------------------------------------------------
# Metric computation
# ---------------------------------------------------------------------------

def compute_metrics(
    predictions: List[str],
    ground_truth: List[str],
    classes: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Compute per-class precision, recall, F1, and macro F1.

    Args:
        predictions: Predicted intent class labels
        ground_truth: Ground truth intent class labels
        classes: Optional explicit class list (auto-detected if None)

    Returns:
        Dict with 'per_class' metrics, 'macro_f1', and 'confusion_matrix'
    """
    if classes is None:
        classes = sorted(set(ground_truth) | set(predictions))

    # Confusion matrix as nested dict: cm[true][pred] = count
    cm: Dict[str, Dict[str, int]] = {c: defaultdict(int) for c in classes}
    for gt, pred in zip(ground_truth, predictions):
        if gt in cm:
            cm[gt][pred] += 1
        else:
            # Unknown true class — add it
            cm[gt] = defaultdict(int)
            cm[gt][pred] += 1

    per_class: Dict[str, Dict[str, float]] = {}
    f1_values: List[float] = []

    for cls in classes:
        # True positives: predicted cls AND true is cls
        tp = cm.get(cls, {}).get(cls, 0)

        # False positives: predicted cls but true is NOT cls
        fp = sum(cm.get(other, {}).get(cls, 0) for other in classes if other != cls)

        # False negatives: true is cls but predicted something else
        fn = sum(cm.get(cls, {}).get(other, 0) for other in classes if other != cls)

        support = tp + fn
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1 = (
            2 * precision * recall / (precision + recall)
            if (precision + recall) > 0
            else 0.0
        )

        per_class[cls] = {
            "precision": round(precision, 4),
            "recall": round(recall, 4),
            "f1": round(f1, 4),
            "support": support,
        }
        if support > 0:
            f1_values.append(f1)

    macro_f1 = sum(f1_values) / len(f1_values) if f1_values else 0.0

    # Serialize confusion matrix (nested dicts → JSON-friendly)
    cm_serializable: Dict[str, Dict[str, int]] = {
        cls: dict(cm.get(cls, {})) for cls in classes
    }

    return {
        "per_class": per_class,
        "macro_f1": round(macro_f1, 4),
        "confusion_matrix": cm_serializable,
    }


def identify_bottom_n(
    per_class: Dict[str, Dict[str, float]],
    n: int = 3,
    exclude: Optional[set] = None,
) -> List[str]:
    """Identify the N worst-performing classes by F1 score.

    Excludes classes with zero support (can't meaningfully measure them).

    Args:
        per_class: Per-class metrics dict from compute_metrics
        n: Number of bottom performers to return
        exclude: Set of class names to exclude from ranking

    Returns:
        List of class names, worst first
    """
    if exclude is None:
        exclude = {"security_critical"}  # Never penalize security_critical in bottom-3

    ranked = [
        (cls, metrics["f1"])
        for cls, metrics in per_class.items()
        if cls not in exclude and metrics.get("support", 0) > 0
    ]
    ranked.sort(key=lambda x: x[1])
    return [cls for cls, _ in ranked[:n]]


# ---------------------------------------------------------------------------
# Classifier wrapper
# ---------------------------------------------------------------------------

def classify_with_real_classifier(prompt: str) -> str:
    """Classify a prompt using the real IntentClassifier.

    Falls back to 'ambiguous' if the classifier is unavailable.

    Args:
        prompt: User prompt to classify

    Returns:
        Intent class string
    """
    try:
        from intent_classifier import IntentClassifier  # type: ignore[import-not-found]
        classifier = IntentClassifier.from_config()
        result = classifier.classify(prompt)
        return result.intent.value if hasattr(result.intent, "value") else str(result.intent)
    except Exception as e:
        # Degrade gracefully if classifier unavailable
        return "ambiguous"


# ---------------------------------------------------------------------------
# Markdown report generation
# ---------------------------------------------------------------------------

def _build_markdown_report(
    per_class: Dict[str, Dict[str, float]],
    macro_f1: float,
    bottom_3: List[str],
    corpus_size: int,
    generated_at: str,
) -> str:
    """Build the Markdown calibration metrics section.

    Args:
        per_class: Per-class metrics
        macro_f1: Macro-averaged F1
        bottom_3: Bottom-3 underperforming classes
        corpus_size: Total corpus entries measured
        generated_at: ISO8601 timestamp

    Returns:
        Markdown string for the calibration section
    """
    lines = [
        _MARKER_BEGIN,
        "## Calibration Metrics (M2, Issue #1043)",
        "",
        f"_Generated at: {generated_at} | Corpus size: {corpus_size}_",
        "",
        f"**Macro F1: {macro_f1:.3f}**",
        "",
        "### Per-Class Metrics",
        "",
        "| Class | Precision | Recall | F1 | Support |",
        "|-------|-----------|--------|----|---------|",
    ]

    for cls in sorted(ALL_CLASSES):
        m = per_class.get(cls, {"precision": 0.0, "recall": 0.0, "f1": 0.0, "support": 0})
        lines.append(
            f"| `{cls}` | {m['precision']:.3f} | {m['recall']:.3f} | {m['f1']:.3f} | {m['support']} |"
        )

    lines += [
        "",
        "### Bottom-3 Underperformers",
        "",
        "These classes had the lowest F1 scores (excluding `security_critical`):",
        "",
    ]
    for i, cls in enumerate(bottom_3, 1):
        m = per_class.get(cls, {"f1": 0.0})
        lines.append(f"{i}. `{cls}` — F1: {m['f1']:.3f}")

    lines += [
        "",
        "**Future work**: Targeted augmentation of training fixtures for the bottom-3 classes "
        "is tracked as a follow-up to Issue #1043. This report MEASURES; the follow-up TUNES.",
        "",
        "### Methodology",
        "",
        "- Corpus: `tests/fixtures/intent_classifier_real_corpus.json`",
        "- Two-judge unanimous agreement (Anthropic + non-Anthropic via OpenRouter)",
        "  OR synthetic-fallback when API keys unavailable",
        "- Holdout entries excluded from accuracy gate but included in support counts",
        "- Regression policy: per-class F1 must not drop >0.05 from baseline; macro F1 must not drop >0.03",
        "",
        _MARKER_END,
    ]
    return "\n".join(lines)


def splice_docs(docs_path: Path, new_section: str) -> None:
    """Idempotently splice the calibration section into INTENT-CLASSIFICATION.md.

    Uses HTML comment markers. If the section already exists, it is replaced.
    If not, it is appended at the end.

    Args:
        docs_path: Path to INTENT-CLASSIFICATION.md
        new_section: Markdown content between the markers (inclusive)
    """
    if not docs_path.exists():
        docs_path.write_text(new_section + "\n")
        return

    content = docs_path.read_text()

    if _MARKER_BEGIN in content and _MARKER_END in content:
        # Replace existing section
        before = content[: content.index(_MARKER_BEGIN)]
        after = content[content.index(_MARKER_END) + len(_MARKER_END) :]
        new_content = before + new_section + after
    else:
        # Append at end
        new_content = content.rstrip() + "\n\n" + new_section + "\n"

    docs_path.write_text(new_content)


# ---------------------------------------------------------------------------
# Main measurement
# ---------------------------------------------------------------------------

def measure_corpus(
    corpus_path: Path,
    *,
    include_holdout: bool = False,
) -> Tuple[Dict[str, Any], List[str], List[str]]:
    """Load corpus and measure classifier performance.

    Args:
        corpus_path: Path to corpus JSON file
        include_holdout: If True, include holdout entries in measurement

    Returns:
        Tuple of (metrics_dict, ground_truth_list, prediction_list)
    """
    corpus = json.loads(corpus_path.read_text())
    entries = corpus.get("entries", [])

    if not include_holdout:
        entries = [e for e in entries if not e.get("holdout", False)]

    ground_truth: List[str] = []
    predictions: List[str] = []

    total = len(entries)
    print(f"INFO: Measuring {total} entries...", file=sys.stderr)

    for i, entry in enumerate(entries):
        if (i + 1) % 10 == 0:
            print(f"INFO: Progress: {i + 1}/{total}", file=sys.stderr)
        gt = entry.get("label", "")
        pred = classify_with_real_classifier(entry["prompt"])
        # Normalize 'ambiguous' to a consistent string
        if pred.lower() in {"ambiguous", "intclass.ambiguous"}:
            pred = "ambiguous"
        ground_truth.append(gt)
        predictions.append(pred)

    all_classes = sorted(ALL_CLASSES | {"ambiguous"})
    metrics = compute_metrics(predictions, ground_truth, classes=sorted(ALL_CLASSES))
    return metrics, ground_truth, predictions


# ---------------------------------------------------------------------------
# Telemetry validation (Issue #1077, Phase B)
# ---------------------------------------------------------------------------

def _iter_mode_skip_rows(path: Path) -> Iterable[Dict[str, Any]]:
    """Yield ``mode_skip`` rows from a hook-blocks JSONL file.

    Wraps ``hook_block_summary._read_jsonl_safely`` and filters to rows whose
    ``decision_shape`` equals ``"mode_skip"``. Malformed JSONL lines are
    skipped silently by the underlying reader.

    Args:
        path: Path to ``hook-blocks.jsonl``

    Yields:
        Dict rows with ``decision_shape == "mode_skip"``
    """
    from hook_block_summary import _read_jsonl_safely  # type: ignore[import-not-found]

    for row in _read_jsonl_safely(path):
        if row.get("_parse_error"):
            continue
        if row.get("decision_shape") == "mode_skip":
            yield row


def _filter_synthetic(rows: Iterable[Dict[str, Any]]) -> Iterable[Dict[str, Any]]:
    """Drop rows with synthetic ``phase-e-test-*`` session IDs or empty IDs.

    Args:
        rows: Iterable of telemetry row dicts

    Yields:
        Rows with non-empty, non-synthetic ``session_id``
    """
    for row in rows:
        sid = row.get("session_id")
        if not isinstance(sid, str) or not sid:
            continue
        if sid.startswith(_SYNTHETIC_SESSION_PREFIX):
            continue
        yield row


def _extract_skip_class(reason: str) -> str:
    """Extract the intent class from a ``mode_skip:<intent_class>`` reason string.

    Args:
        reason: The ``reason`` field from a telemetry row

    Returns:
        The intent class name, or ``"unknown"`` if malformed
    """
    if not isinstance(reason, str):
        return "unknown"
    m = _MODE_SKIP_REASON_RE.match(reason)
    if not m:
        return "unknown"
    return m.group(1)


def _load_session_metadata(
    db_path: Path, session_ids: Set[str]
) -> Dict[str, Dict[str, Any]]:
    """Load session metadata for the given session IDs from sessions.db.

    Returns an empty dict if the database file is missing or the ``sessions``
    table is missing. Chunks the query at 500 IDs to stay under the SQLite
    parameter limit.

    Args:
        db_path: Path to ``sessions.db``
        session_ids: Set of session IDs to fetch

    Returns:
        Mapping of ``session_id`` to a dict with keys: ``first_user_prompt``,
        ``tool_calls``, ``transcript_bytes``, ``message_count``. Missing IDs
        are simply absent from the result.
    """
    if not db_path.exists() or not session_ids:
        return {}

    result: Dict[str, Dict[str, Any]] = {}
    ids_list = list(session_ids)
    chunk_size = 500
    try:
        with sqlite3.connect(str(db_path)) as conn:
            for start in range(0, len(ids_list), chunk_size):
                chunk = ids_list[start : start + chunk_size]
                placeholders = ",".join(["?"] * len(chunk))
                query = (
                    "SELECT session_id, first_user_prompt, tool_calls, "
                    "transcript_bytes, message_count FROM sessions "
                    f"WHERE session_id IN ({placeholders})"
                )
                cursor = conn.execute(query, chunk)
                for row in cursor.fetchall():
                    sid, prompt, tool_calls, tbytes, mcount = row
                    result[sid] = {
                        "first_user_prompt": prompt,
                        "tool_calls": tool_calls,
                        "transcript_bytes": tbytes,
                        "message_count": mcount,
                    }
    except sqlite3.OperationalError:
        return {}

    return result


def _is_implement_shaped(
    session_meta: Optional[Dict[str, Any]]
) -> Tuple[bool, str]:
    """Classify a session as implement-shaped via regex-then-aggregate.

    Three-tier heuristic:
        1. Regex match on ``first_user_prompt`` for ``/implement``,
           ``/refactor``, or ``/fix`` -> (True, "regex")
        2. Aggregate match: ``tool_calls >= 8`` AND
           ``transcript_bytes >= 4096`` -> (True, "aggregate")
        3. Otherwise -> (False, "no_signal") or (False, "no_metadata")

    Args:
        session_meta: Session metadata dict, or None if not found in DB

    Returns:
        Tuple of (is_implement_shaped, reason_label)
    """
    if session_meta is None:
        return (False, "no_metadata")
    prompt = session_meta.get("first_user_prompt") or ""
    if not isinstance(prompt, str):
        return (False, "no_signal")
    for pat in _IMPLEMENT_REGEX_PATTERNS:
        if pat.search(prompt):
            return (True, "regex")
    tool_calls = session_meta.get("tool_calls") or 0
    transcript_bytes = session_meta.get("transcript_bytes") or 0
    if (
        tool_calls >= _AGGREGATE_TOOL_THRESHOLD
        and transcript_bytes >= _AGGREGATE_BYTES_THRESHOLD
    ):
        return (True, "aggregate")
    return (False, "no_signal")


def _wilson_ci(
    successes: int, n: int, z: float = 1.96
) -> Tuple[float, float]:
    """Wilson score 95% CI for a binomial proportion.

    Edge cases: ``n<=0`` returns ``(0.0, 1.0)``; ``successes==0`` returns
    ``ci_low=0.0``; ``successes==n`` returns ``ci_high=1.0``.

    Formula (canonical Wikipedia form):
        (p + z^2/2n +/- z * sqrt(p(1-p)/n + z^2/4n^2)) / (1 + z^2/n)

    Args:
        successes: Number of successes
        n: Total trials
        z: z-score (default 1.96 for 95% CI)

    Returns:
        Tuple of (ci_low, ci_high), each in [0.0, 1.0]
    """
    if n <= 0:
        return (0.0, 1.0)
    p_hat = successes / n
    z2 = z * z
    denom = 1.0 + z2 / n
    centre = (p_hat + z2 / (2 * n)) / denom
    margin = (z * math.sqrt(p_hat * (1 - p_hat) / n + z2 / (4 * n * n))) / denom
    return (max(0.0, centre - margin), min(1.0, centre + margin))


def validate_from_telemetry(
    *,
    telemetry_log: Path,
    sessions_db: Path,
) -> Dict[str, Any]:
    """Validate intent-classifier FN rate from real telemetry.

    Reads ``mode_skip`` rows from the hook telemetry JSONL, joins by
    ``session_id`` against ``sessions.db``, classifies each session as
    implement-shaped via regex-then-aggregate heuristic, and computes
    observed FN rate with Wilson 95% CI.

    Args:
        telemetry_log: Path to ``hook-blocks.jsonl``
        sessions_db: Path to ``sessions.db``

    Returns:
        Result dict matching the schema in the Phase B plan §4.
    """
    # 1. Read all mode_skip rows.
    all_skip_rows: List[Dict[str, Any]] = list(_iter_mode_skip_rows(telemetry_log))
    n_total_skip_rows = len(all_skip_rows)

    # 2. Filter synthetic rows. Track count.
    n_synthetic_filtered = 0
    real_rows: List[Dict[str, Any]] = []
    for row in all_skip_rows:
        sid = row.get("session_id")
        if not isinstance(sid, str) or not sid:
            n_synthetic_filtered += 1
            continue
        if sid.startswith(_SYNTHETIC_SESSION_PREFIX):
            n_synthetic_filtered += 1
            continue
        real_rows.append(row)

    # 3. Build deduped session_id -> skip_class map (first occurrence wins).
    sid_to_skip_class: Dict[str, str] = {}
    for row in real_rows:
        sid = row["session_id"]
        if sid in sid_to_skip_class:
            continue
        sid_to_skip_class[sid] = _extract_skip_class(row.get("reason", ""))

    n_unique_sessions = len(sid_to_skip_class)

    # 4. Load session metadata.
    session_meta_map: Dict[str, Dict[str, Any]] = _load_session_metadata(
        sessions_db, set(sid_to_skip_class.keys())
    )

    # 5. Per-session classification + per-class breakdown.
    n_implement_sessions = 0
    n_no_metadata = 0
    breakdown: Dict[str, Dict[str, int]] = defaultdict(
        lambda: {"total": 0, "implement_shaped": 0}
    )

    for sid, skip_class in sid_to_skip_class.items():
        meta = session_meta_map.get(sid)
        is_implement, reason = _is_implement_shaped(meta)
        breakdown[skip_class]["total"] += 1
        if is_implement:
            n_implement_sessions += 1
            breakdown[skip_class]["implement_shaped"] += 1
        if reason == "no_metadata":
            n_no_metadata += 1

    # n_skipped == n_implement_sessions: every implement-shaped session that
    # hit mode_skip is by definition a false negative; numerator equals
    # denominator for this measurement.
    n_skipped = n_implement_sessions

    # 6. Compute observed FN rate + Wilson CI.
    if n_unique_sessions > 0:
        observed_fn_rate = n_implement_sessions / n_unique_sessions
    else:
        observed_fn_rate = 0.0
    ci_low, ci_high = _wilson_ci(n_implement_sessions, n_unique_sessions)

    # 7. Insufficient-sample warning + diagnostic message.
    insufficient_sample_warning = n_unique_sessions < _INSUFFICIENT_SAMPLE_THRESHOLD

    diagnostic_message: Optional[str]
    if n_total_skip_rows == 0:
        diagnostic_message = (
            "No mode_skip telemetry rows found. Phase A telemetry collection "
            "may not yet be operational."
        )
    elif n_unique_sessions == 0:
        diagnostic_message = (
            "All telemetry rows filtered as synthetic (phase-e-test-* prefix). "
            "Phase A collection not yet operational."
        )
    elif not sessions_db.exists():
        diagnostic_message = f"sessions.db not found at {sessions_db}"
    elif n_no_metadata == n_unique_sessions:
        diagnostic_message = (
            "No session metadata available; sessions.db may be missing or empty."
        )
    else:
        diagnostic_message = None

    # 8. Build result dict per §4 schema.
    result: Dict[str, Any] = {
        "_meta": {
            "schema_version": _TELEMETRY_SCHEMA_VERSION,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "telemetry_log": str(telemetry_log.resolve()) if telemetry_log.exists() else str(telemetry_log),
            "sessions_db": str(sessions_db.resolve()) if sessions_db.exists() else str(sessions_db),
            "issue": "#1077",
        },
        "n_total_skip_rows": n_total_skip_rows,
        "n_synthetic_filtered": n_synthetic_filtered,
        "n_unique_sessions": n_unique_sessions,
        "n_implement_sessions": n_implement_sessions,
        "n_skipped": n_skipped,
        "n_no_metadata": n_no_metadata,
        "observed_fn_rate": observed_fn_rate,
        "ci_low": ci_low,
        "ci_high": ci_high,
        "insufficient_sample_warning": insufficient_sample_warning,
        "diagnostic_message": diagnostic_message,
        "per_skip_class_breakdown": {k: dict(v) for k, v in breakdown.items()},
    }
    return result


def _main_validate_from_telemetry(args: argparse.Namespace) -> int:
    """CLI dispatcher for ``--validate-from-telemetry`` mode.

    Args:
        args: Parsed argparse namespace with ``telemetry_log``,
            ``sessions_db``, and ``telemetry_output`` attributes.

    Returns:
        Process exit code (0 on success).
    """
    telemetry_log: Path = args.telemetry_log
    sessions_db: Path = args.sessions_db
    output_path: Path = args.telemetry_output

    result = validate_from_telemetry(
        telemetry_log=telemetry_log,
        sessions_db=sessions_db,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")

    print("\n" + "=" * 60, file=sys.stderr)
    print("INTENT CLASSIFIER TELEMETRY VALIDATION (Issue #1077)", file=sys.stderr)
    print("=" * 60, file=sys.stderr)
    print(f"Telemetry log:     {telemetry_log}", file=sys.stderr)
    print(f"Sessions DB:       {sessions_db}", file=sys.stderr)
    print(f"Total skip rows:   {result['n_total_skip_rows']}", file=sys.stderr)
    print(f"Synthetic filtered:{result['n_synthetic_filtered']}", file=sys.stderr)
    print(f"Unique sessions:   {result['n_unique_sessions']}", file=sys.stderr)
    print(f"Implement-shaped:  {result['n_implement_sessions']}", file=sys.stderr)
    print(f"No metadata:       {result['n_no_metadata']}", file=sys.stderr)
    print(
        f"Observed FN rate:  {result['observed_fn_rate']:.4f} "
        f"(CI: [{result['ci_low']:.4f}, {result['ci_high']:.4f}])",
        file=sys.stderr,
    )
    if result["insufficient_sample_warning"]:
        print(
            f"WARNING: insufficient sample (n < {_INSUFFICIENT_SAMPLE_THRESHOLD})",
            file=sys.stderr,
        )
    if result["diagnostic_message"]:
        print(f"DIAGNOSTIC: {result['diagnostic_message']}", file=sys.stderr)
    print(f"Result written to: {output_path}", file=sys.stderr)
    print("=" * 60, file=sys.stderr)
    return 0


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """CLI entry point for measurement."""
    parser = argparse.ArgumentParser(
        description="Measure IntentClassifier accuracy against corpus"
    )
    # Telemetry validation flags (Issue #1077, Phase B)
    parser.add_argument(
        "--validate-from-telemetry",
        action="store_true",
        help=(
            "Validate observed FN rate from real mode_skip telemetry "
            "rather than running the corpus measurement (Issue #1077)."
        ),
    )
    parser.add_argument(
        "--telemetry-log",
        type=Path,
        default=_DEFAULT_TELEMETRY_LOG,
        help="Path to hook-blocks.jsonl (telemetry source)",
    )
    parser.add_argument(
        "--sessions-db",
        type=Path,
        default=_DEFAULT_SESSIONS_DB,
        help="Path to sessions.db (session metadata source)",
    )
    parser.add_argument(
        "--telemetry-output",
        type=Path,
        default=_DEFAULT_TELEMETRY_OUTPUT,
        help="Output path for telemetry validation JSON",
    )
    # Existing flags
    parser.add_argument(
        "--corpus-path",
        type=Path,
        default=_DEFAULT_CORPUS,
        help="Path to corpus JSON file",
    )
    parser.add_argument(
        "--baseline-output",
        type=Path,
        default=_DEFAULT_BASELINE,
        help="Output path for baseline JSON",
    )
    parser.add_argument(
        "--update-docs",
        action="store_true",
        help="Splice calibration metrics into docs/INTENT-CLASSIFICATION.md",
    )
    parser.add_argument(
        "--include-holdout",
        action="store_true",
        help="Include holdout entries in measurement",
    )
    args = parser.parse_args()

    # Branch into telemetry-validation mode immediately after parse.
    if args.validate_from_telemetry:
        sys.exit(_main_validate_from_telemetry(args))

    if not args.corpus_path.exists():
        print(f"ERROR: Corpus file not found: {args.corpus_path}", file=sys.stderr)
        sys.exit(1)

    metrics, ground_truth, predictions = measure_corpus(
        args.corpus_path,
        include_holdout=args.include_holdout,
    )

    per_class = metrics["per_class"]
    macro_f1 = metrics["macro_f1"]

    bottom_3 = identify_bottom_n(per_class, n=3, exclude={"security_critical"})

    corpus = json.loads(args.corpus_path.read_text())
    corpus_size = len(corpus.get("entries", []))

    generated_at = datetime.now(timezone.utc).isoformat()

    baseline = {
        "_schema_version": 1,
        "generated_at": generated_at,
        "corpus_size": corpus_size,
        "per_class": per_class,
        "macro_f1": macro_f1,
        "confusion_matrix": metrics["confusion_matrix"],
        "bottom_3_underperformers": bottom_3,
    }

    # Print summary
    print("\n" + "=" * 60)
    print("INTENT CLASSIFIER CALIBRATION RESULTS")
    print("=" * 60)
    print(f"Corpus size: {corpus_size}")
    print(f"Macro F1: {macro_f1:.4f}")
    print()
    print(f"{'Class':<20} {'Precision':>10} {'Recall':>10} {'F1':>10} {'Support':>8}")
    print("-" * 62)
    for cls in sorted(ALL_CLASSES):
        m = per_class.get(cls, {"precision": 0.0, "recall": 0.0, "f1": 0.0, "support": 0})
        print(
            f"{cls:<20} {m['precision']:>10.3f} {m['recall']:>10.3f} "
            f"{m['f1']:>10.3f} {m['support']:>8}"
        )
    print()
    print(f"Bottom-3 underperformers (excl. security_critical): {bottom_3}")
    print("=" * 60)

    # Write baseline
    args.baseline_output.parent.mkdir(parents=True, exist_ok=True)
    args.baseline_output.write_text(json.dumps(baseline, indent=2))
    print(f"INFO: Baseline written to {args.baseline_output}", file=sys.stderr)

    # Update docs if requested
    if args.update_docs:
        markdown = _build_markdown_report(
            per_class, macro_f1, bottom_3, corpus_size, generated_at
        )
        splice_docs(_DEFAULT_DOCS_PATH, markdown)
        print(
            f"INFO: Calibration metrics spliced into {_DEFAULT_DOCS_PATH}",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
