"""Acceptance tests for: Issue #918 — Coordinator blocked on READ of settings.local.json

Generated by acceptance-first pipeline mode.

Issue #918 reports that the hook write-protect logic appeared to fire on Read tool
calls targeting .claude/settings.local.json. Research confirmed the production code
is already correctly tool-name-gated at unified_pre_tool.py:4457 (Write/Edit gate)
and :4685 (Bash gate). The scope of this fix is to LOCK the correct behaviour in
place with a regression test class.

All criteria below are static file inspections (per STEP 6 placement classification
rule, those technically belong in tests/unit/, but we follow the existing
tests/genai/test_acceptance_*.py convention of marking acceptance criteria with
@pytest.mark.genai for traceability).
"""

import subprocess
import sys
from pathlib import Path


# Repo root: tests/unit/<file>.py -> parents[0]=tests/unit, [1]=tests, [2]=repo root.
# Derived locally (matches the tests/unit/test_acceptance_*.py convention); the former
# `from .conftest import PROJECT_ROOT` was a tests/genai/ coupling that did not move.
PROJECT_ROOT = Path(__file__).resolve().parents[2]

REGRESSION_TEST_FILE = (
    PROJECT_ROOT
    / "tests"
    / "unit"
    / "hooks"
    / "test_unified_pre_tool_false_positives.py"
)

_LIB = PROJECT_ROOT / "plugins" / "autonomous-dev" / "lib"
if str(_LIB) not in sys.path:
    sys.path.insert(0, str(_LIB))

UNIFIED_PRE_TOOL = (
    PROJECT_ROOT / "plugins/autonomous-dev/hooks/unified_pre_tool.py"
)


class TestAcceptanceIssue918:
    """Acceptance criteria from Issue #918."""

    def test_ac1_regression_class_exists(self):
        """AC1: New test class TestIssue918ReadToolNeverBlocksSettings exists."""
        content = REGRESSION_TEST_FILE.read_text()
        assert "class TestIssue918ReadToolNeverBlocksSettings" in content, (
            "Regression test class TestIssue918ReadToolNeverBlocksSettings must "
            f"exist in {REGRESSION_TEST_FILE.relative_to(PROJECT_ROOT)}"
        )

    def test_ac2_regression_class_docstring_cites_issue_and_lines(self):
        """AC2: Class docstring cites Issue #918 and gate line numbers 4457 and 4685."""
        content = REGRESSION_TEST_FILE.read_text()
        idx = content.find("class TestIssue918ReadToolNeverBlocksSettings")
        assert idx != -1, "Regression class must exist before docstring check"
        # Look at the next ~1500 chars for the class docstring
        window = content[idx : idx + 1500]
        assert "#918" in window or "Issue 918" in window, (
            "Class docstring must cite Issue #918"
        )
        assert "4457" in window, (
            "Class docstring must cite the Write/Edit gate line number 4457"
        )
        assert "4685" in window, (
            "Class docstring must cite the Bash gate line number 4685"
        )

    def test_ac3_regression_tests_pass(self):
        """AC3: All new regression tests PASS via pytest."""
        result = subprocess.run(
            [
                "pytest",
                str(REGRESSION_TEST_FILE),
                "-v",
                "--tb=short",
                "-k",
                "TestIssue918ReadToolNeverBlocksSettings",
            ],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            timeout=120,
        )
        assert result.returncode == 0, (
            f"Regression tests must pass. stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )

    def test_ac4_write_protect_gate_never_classifies_read_as_a_write(self):
        """AC4: the write-protect path stays gated so Read can never enter it.

        WHY THIS ASSERTION CHANGED (stale as of Issue #1503; test relocated
        from tests/genai/ to tests/unit/):

        The original AC4 pinned two hardcoded line numbers in
        unified_pre_tool.py — 4457 (`tool_name in ("Write", "Edit")`) and 4685
        (`tool_name == "Bash"`) — with a +/-5 line drift window. Both anchors
        are now stale, for two INDEPENDENT reasons:

        1. Line drift. At the commit that added this test (039474b) the hook
           was 5,358 lines and line 4457 was exactly the Write/Edit gate.
           The file is now 9,382 lines, so the window points at unrelated code.
        2. The literal string was deliberately retired. Issue #1503 moved that
           gate into `_enforce_protected_infrastructure()` and REPLACED the
           `tool_name in ("Write", "Edit")` tuple test with the broader
           `tool_intent.is_write()` classification, so the hard floor also
           reaches MultiEdit, NotebookEdit and MCP editors. The hook's own
           docstring records the change.

        So this is a stale test, NOT a production defect: the gate still
        exists and is strictly BROADER than what AC4 was written against.
        Rather than re-pin a new line number (which would go stale the same
        way), AC4 now asserts the MECHANISM and the BEHAVIOUR that Issue #918
        actually cares about — and it is two-armed: the classifier must refuse
        Read (the #918 bug) AND permit genuine writes (proving it can fire).
        """
        source = UNIFIED_PRE_TOOL.read_text()

        # Structural arm: the gate exists and is intent-gated, wherever it lives.
        assert "def _enforce_protected_infrastructure(" in source, (
            "The protected-infrastructure write gate must still exist in "
            "unified_pre_tool.py — Issue #918 depends on it being tool-gated"
        )
        assert "_ti_is_write(tool_name, tool_input)" in source, (
            "The write-protect gate must classify by write-intent. Without an "
            "intent gate every tool (including Read) reaches the block path, "
            "which is precisely the Issue #918 regression."
        )
        assert 'tool_name == "Bash"' in source, (
            "The Bash tool-name gate must still exist in unified_pre_tool.py"
        )

        # Behavioural arm: watch the classifier REFUSE and PERMIT.
        import tool_intent

        settings = {"file_path": str(PROJECT_ROOT / ".claude/settings.local.json")}

        # Refusing arm — Read must never be write-classified (the #918 bug).
        assert tool_intent.is_write("Read", settings) is False, (
            "Read on settings.local.json must NOT be classified as a write — "
            "this is the exact Issue #918 false positive"
        )
        # Permitting arm — proves the classifier can actually fire, so the
        # refusing arm above is a real result and not a check that cannot fail.
        assert tool_intent.is_write("Write", settings) is True, (
            "Write on settings.local.json MUST be write-classified — if this "
            "fails the Read assertion above is vacuous"
        )
        assert tool_intent.is_write("Edit", settings) is True, (
            "Edit on settings.local.json MUST be write-classified"
        )
