"""Acceptance tests for Issue #1133 — /implement --batch --no-worktree mode.

Generated by acceptance-first pipeline mode. Static-inspection acceptance checks;
deeper behavioral verification lives in the integration suite
(tests/integration/test_no_worktree_cluster_3_issues.py).

The acceptance criteria are structural (flag presence, function existence,
hook helper exists, doc updates), so these tests use file content inspection
rather than LLM judges. Per STEP 6 classification rule: static checks belong
in tests/unit/ without @pytest.mark.genai.
"""

from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).parent.parent.parent


class TestAcceptance1133NoWorktree:
    """Issue #1133 acceptance criteria."""

    # ------------------------------------------------------------------
    # AC1 — --no-worktree flag accepted by /implement --batch,
    # documented in commands/implement.md.
    # ------------------------------------------------------------------

    def test_ac1_flag_recognized_by_orchestrator(self):
        """parse_implement_flags must recognize --no-worktree."""
        content = (
            PROJECT_ROOT / "plugins/autonomous-dev/lib/batch_orchestrator.py"
        ).read_text()
        assert "no_worktree" in content, (
            "batch_orchestrator.py must reference no_worktree (the parsed flag field)."
        )
        assert "--no-worktree" in content, (
            "batch_orchestrator.py must reference the --no-worktree CLI flag."
        )

    def test_ac1_flag_documented_in_implement_md(self):
        """commands/implement.md must document --no-worktree."""
        content = (
            PROJECT_ROOT / "plugins/autonomous-dev/commands/implement.md"
        ).read_text()
        assert "--no-worktree" in content, (
            "commands/implement.md must document the --no-worktree modifier flag."
        )

    # ------------------------------------------------------------------
    # AC2 — A function equivalent to implement_batch_in_place(issue_numbers)
    # exists in lib/batch_orchestrator.py (canonical name:
    # run_batch_no_worktree_mode per ADR-001 of the revised plan).
    # ------------------------------------------------------------------

    def test_ac2_no_worktree_function_exists(self):
        """run_batch_no_worktree_mode must be defined in batch_orchestrator.py."""
        content = (
            PROJECT_ROOT / "plugins/autonomous-dev/lib/batch_orchestrator.py"
        ).read_text()
        assert "def run_batch_no_worktree_mode(" in content, (
            "batch_orchestrator.py must define run_batch_no_worktree_mode "
            "(the in-place cluster execution entry point)."
        )

    # ------------------------------------------------------------------
    # AC3 — Single PR opened at end of batch with multi-issue title.
    # ------------------------------------------------------------------

    def test_ac3_cluster_pr_helper_exists(self):
        """A helper that opens a multi-issue PR must exist."""
        content = (
            PROJECT_ROOT / "plugins/autonomous-dev/lib/batch_git_finalize.py"
        ).read_text()
        # Either open_cluster_pr() or mode="no_worktree" parameterization of
        # the existing finalize satisfies AC3 per ADR-001.
        has_open_cluster_pr = "def open_cluster_pr(" in content
        has_no_worktree_mode = "no_worktree" in content
        assert has_open_cluster_pr or has_no_worktree_mode, (
            "batch_git_finalize.py must support multi-issue PR creation via either "
            "open_cluster_pr() helper or mode='no_worktree' parameterization."
        )

    # ------------------------------------------------------------------
    # AC4 — scripts/drain-all.sh --cluster-mode queries issue_triage_analyzer
    # and invokes /implement --batch --no-worktree.
    # ------------------------------------------------------------------

    def test_ac4_drain_all_cluster_mode_flag(self):
        """scripts/drain-all.sh must recognize --cluster-mode flag."""
        path = PROJECT_ROOT / "scripts/drain-all.sh"
        assert path.exists(), "scripts/drain-all.sh must exist."
        content = path.read_text()
        assert "--cluster-mode" in content, (
            "scripts/drain-all.sh must implement the --cluster-mode flag."
        )
        assert "--no-worktree" in content, (
            "scripts/drain-all.sh --cluster-mode must invoke /implement with --no-worktree."
        )

    # ------------------------------------------------------------------
    # AC5 — scripts/triage-and-implement.sh updated to use cluster mode
    # by default; old per-issue serial path preserved as --no-cluster fallback.
    # ------------------------------------------------------------------

    def test_ac5_triage_and_implement_cluster_default(self):
        """triage-and-implement.sh must support --no-cluster legacy flag."""
        path = PROJECT_ROOT / "scripts/triage-and-implement.sh"
        assert path.exists(), "scripts/triage-and-implement.sh must exist."
        content = path.read_text()
        # New default invokes --no-worktree; legacy is --no-cluster
        assert "--no-cluster" in content or "no_cluster" in content, (
            "scripts/triage-and-implement.sh must preserve the legacy per-issue "
            "serial loop behind a --no-cluster flag."
        )

    # ------------------------------------------------------------------
    # AC6 — Integration test: synthetic 3-issue cluster → one PR closes
    # all 3 (test file existence + AC mapping; deep behavior verified
    # by the integration test runner in STEP 8).
    # ------------------------------------------------------------------

    def test_ac6_integration_test_exists(self):
        """tests/integration/test_no_worktree_cluster_3_issues.py must exist."""
        path = (
            PROJECT_ROOT
            / "tests/integration/test_no_worktree_cluster_3_issues.py"
        )
        assert path.exists(), (
            "tests/integration/test_no_worktree_cluster_3_issues.py must exist "
            "to verify the 3-issue cluster end-to-end flow."
        )
        content = path.read_text()
        assert "Closes #" in content or "Closes #N" in content, (
            "Integration test must verify 'Closes #N' lines in PR body."
        )

    # ------------------------------------------------------------------
    # AC7 — Regression: existing single-issue and --batch <file> worktree
    # modes still work (no behavior regression in consumer repos).
    # ------------------------------------------------------------------

    def test_ac7_regression_coverage_in_unit_tests(self):
        """Unit tests must cover regression of existing modes."""
        path = (
            PROJECT_ROOT
            / "tests/unit/lib/test_batch_orchestrator_no_worktree.py"
        )
        assert path.exists(), (
            "tests/unit/lib/test_batch_orchestrator_no_worktree.py must exist "
            "(includes regression cases for existing --batch and --issues modes)."
        )

    def test_ac7_hook_helper_unit_tests_exist(self):
        """Hook gate unit tests must exist."""
        path = PROJECT_ROOT / "tests/unit/hooks/test_no_worktree_batch_gate.py"
        assert path.exists(), (
            "tests/unit/hooks/test_no_worktree_batch_gate.py must exist "
            "to verify _is_batch_context helper and gate firing in no-worktree mode."
        )

    # ------------------------------------------------------------------
    # AC8 — Drain time-per-cluster-success measured (≥40% reduction).
    # Per revised plan ADR: documented as a manual perf-smoke procedure
    # in docs/RUNBOOK.md instead of a synthetic mocked test.
    # ------------------------------------------------------------------

    def test_ac8_runbook_perf_smoke_documented(self):
        """docs/RUNBOOK.md must document the manual perf-smoke procedure."""
        path = PROJECT_ROOT / "docs/RUNBOOK.md"
        assert path.exists(), "docs/RUNBOOK.md must exist."
        content = path.read_text().lower()
        # Must reference either --cluster-mode or --no-worktree timing
        assert "cluster-mode" in content or "no-worktree" in content, (
            "docs/RUNBOOK.md must document the cluster-mode / --no-worktree "
            "perf-smoke procedure (AC8)."
        )
